protection:
  branches:
    main:
      required_status_checks:
        strict: true
        contexts:
          - "Build and Test"
          - "Security Scan"
      required_pull_request_reviews:
        required_approving_review_count: 2
      restrictions:
        teams: ["admins"]

    produccion:
      required_status_checks:
        strict: true
        contexts:
          - "Build and Test"
          - "Security Scan"
          - "Compliance Check"
      required_pull_request_reviews:
        required_approving_review_count: 2
      restrictions:
        teams: ["releases"]

    qa:
      required_status_checks:
        strict: true
        contexts:
          - "Build and Test"
      required_pull_request_reviews:
        required_approving_review_count: 1