# Secret Management para VUCEM - Enfoque Open Source
# Basado en External Secrets Operator + HashiCorp Vault OSS

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vucem-vault-backend
  namespace: vucem-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    mx.gob.vucem/environment: ${ENVIRONMENT}
spec:
  provider:
    vault:
      server: "https://vault.vucem.internal"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vucem-${ENVIRONMENT}-role"
          secretRef:
            name: vault-auth-secret
            key: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vucem-app-secrets
  namespace: vucem-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: external-secrets
    mx.gob.vucem/component: ${COMPONENT_NAME}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vucem-vault-backend
    kind: SecretStore
  target:
    name: vucem-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          mx.gob.vucem/managed-by: external-secrets
      data:
        # Secretos de base de datos
        SPRING_DATASOURCE_PASSWORD: "{{ .db_password }}"
        SPRING_DATASOURCE_USERNAME: "{{ .db_username }}"
        
        # Secretos JWT
        JWT_SECRET_KEY: "{{ .jwt_secret }}"
        JWT_REFRESH_SECRET: "{{ .jwt_refresh_secret }}"
        
        # Secretos de integración
        VUCEM_API_KEY: "{{ .vucem_api_key }}"
        EXTERNAL_SERVICE_TOKEN: "{{ .external_service_token }}"
        
        # Certificados SSL/TLS
        TLS_CERT: "{{ .tls_cert }}"
        TLS_KEY: "{{ .tls_key }}"
  data:
  - secretKey: db_password
    remoteRef:
      key: "vucem/${ENVIRONMENT}/${COMPONENT_NAME}/database"
      property: password
  - secretKey: db_username
    remoteRef:
      key: "vucem/${ENVIRONMENT}/${COMPONENT_NAME}/database"
      property: username
  - secretKey: jwt_secret
    remoteRef:
      key: "vucem/${ENVIRONMENT}/${COMPONENT_NAME}/auth"
      property: jwt_secret
  - secretKey: jwt_refresh_secret
    remoteRef:
      key: "vucem/${ENVIRONMENT}/${COMPONENT_NAME}/auth"
      property: jwt_refresh_secret
  - secretKey: vucem_api_key
    remoteRef:
      key: "vucem/${ENVIRONMENT}/shared"
      property: api_key
  - secretKey: external_service_token
    remoteRef:
      key: "vucem/${ENVIRONMENT}/${COMPONENT_NAME}/integrations"
      property: service_token
  - secretKey: tls_cert
    remoteRef:
      key: "vucem/${ENVIRONMENT}/tls"
      property: certificate
  - secretKey: tls_key
    remoteRef:
      key: "vucem/${ENVIRONMENT}/tls"
      property: private_key
---
# ConfigMap para configuración no sensible
apiVersion: v1
kind: ConfigMap
metadata:
  name: vucem-app-config
  namespace: vucem-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: vucem-component
    mx.gob.vucem/component: ${COMPONENT_NAME}
    mx.gob.vucem/environment: ${ENVIRONMENT}
data:
  # Configuración de aplicación
  SPRING_PROFILES_ACTIVE: "${ENVIRONMENT}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/vucem_${COMPONENT_NAME}_${ENVIRONMENT}"
  
  # Configuración de observabilidad
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  
  # Configuración de seguridad
  SPRING_SECURITY_REQUIRE_SSL: "true"
  SERVER_SSL_ENABLED: "true"
  
  # Configuración específica de VUCEM
  VUCEM_API_BASE_URL: "https://api.vucem.gob.mx"
  VUCEM_COMPONENT_NAME: "${COMPONENT_NAME}"
  VUCEM_ENVIRONMENT: "${ENVIRONMENT}"
  
  # Configuración de logging
  LOGGING_LEVEL_MX_GOB_VUCEM: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  
  # Configuración de resiliencia
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_FAILURE_RATE_THRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_WAIT_DURATION_IN_OPEN_STATE: "30s"
  RESILIENCE4J_RETRY_INSTANCES_DEFAULT_MAX_ATTEMPTS: "3"
---
# Política de red para restringir acceso a secretos
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vucem-secret-access-policy
  namespace: vucem-${ENVIRONMENT}
  labels:
    mx.gob.vucem/component: security
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: vucem-${ENVIRONMENT}
    - podSelector:
        matchLabels:
          mx.gob.vucem/authorized: "true"
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: vault-system
    ports:
    - protocol: TCP
      port: 8200
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53