name: Reporte de Vulnerabilidad de Seguridad
description: Reportar una vulnerabilidad de seguridad (acceso privado)
title: "[SECURITY]: "
labels: ["security", "confidential"]
assignees:
  - equipo-seguridad

body:
  - type: markdown
    attributes:
      value: |
        # IMPORTANTE
        Este formulario es para reportar vulnerabilidades de seguridad. Los reportes enviados a través de este formulario serán visibles únicamente para los mantenedores del proyecto.
        
        Si ha encontrado una vulnerabilidad que podría comprometer la seguridad de los usuarios o sistemas, agradecemos su responsabilidad en reportarla de manera confidencial.

  - type: dropdown
    id: tipo-vulnerabilidad
    attributes:
      label: Tipo de vulnerabilidad
      description: ¿Qué tipo de vulnerabilidad ha identificado?
      options:
        - Inyección SQL
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Exposición de datos sensibles
        - Configuración incorrecta de seguridad
        - Autenticación o autorización débil
        - Otro (especificar en la descripción)
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripción de la vulnerabilidad
      description: Proporcione detalles sobre la vulnerabilidad y cómo la descubrió.
      placeholder: He identificado que el endpoint /api/recursos permite...
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: Impacto potencial
      description: Describa el impacto que esta vulnerabilidad podría tener si se explotara.
    validations:
      required: true

  - type: textarea
    id: reproduccion
    attributes:
      label: Pasos para reproducir
      description: Proporcione los pasos detallados para reproducir la vulnerabilidad.
      placeholder: |
        1. Acceder a la URL con el siguiente parámetro...
        2. Modificar la solicitud HTTP para incluir...
        3. Observar que el sistema...
    validations:
      required: true

  - type: textarea
    id: mitigacion
    attributes:
      label: Sugerencia de mitigación
      description: Si tiene alguna sugerencia sobre cómo solucionar esta vulnerabilidad, por favor inclúyala.
    validations:
      required: false

  - type: dropdown
    id: severidad
    attributes:
      label: Severidad estimada
      description: Basado en el impacto y la facilidad de explotación, ¿cómo calificaría la severidad?
      options:
        - Crítica
        - Alta
        - Media
        - Baja
    validations:
      required: true

  - type: checkboxes
    id: confirmaciones
    attributes:
      label: Confirmaciones
      description: Por favor confirme lo siguiente
      options:
        - label: No he compartido ni compartiré esta vulnerabilidad públicamente hasta que haya sido resuelta
          required: true
        - label: Entiendo que este reporte será manejado de manera confidencial
          required: true