version: '3.8'

services:
  sonarqube:
    image: sonarqube:10.3-community
    container_name: vucem-sonarqube
    hostname: sonarqube
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_CONTEXT: /sonarqube
      SONAR_WEB_PORT: 9000
      SONAR_CE_JAVAOPTS: -Xmx2g
      SONAR_WEB_JAVAOPTS: -Xmx1g
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_conf:/opt/sonarqube/conf
    ports:
      - "9000:9000"
    networks:
      - vucem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/sonarqube/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "mx.gob.vucem.service=sonarqube"
      - "mx.gob.vucem.environment=devtools"
      - "mx.gob.vucem.component=quality-gate"

  sonardb:
    image: postgres:15-alpine
    container_name: vucem-sonardb
    hostname: sonardb
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    networks:
      - vucem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "mx.gob.vucem.service=sonardb"
      - "mx.gob.vucem.environment=devtools"
      - "mx.gob.vucem.component=database"

  # Proxy reverso para SonarQube con SSL
  sonar-proxy:
    image: nginx:alpine
    container_name: vucem-sonar-proxy
    depends_on:
      - sonarqube
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/sonar.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - vucem-network
    restart: unless-stopped
    labels:
      - "mx.gob.vucem.service=sonar-proxy"
      - "mx.gob.vucem.environment=devtools"
      - "mx.gob.vucem.component=proxy"

volumes:
  sonarqube_data:
    driver: local
    labels:
      - "mx.gob.vucem.volume=sonarqube-data"
  sonarqube_logs:
    driver: local
    labels:
      - "mx.gob.vucem.volume=sonarqube-logs"
  sonarqube_extensions:
    driver: local
    labels:
      - "mx.gob.vucem.volume=sonarqube-extensions"
  sonarqube_conf:
    driver: local
    labels:
      - "mx.gob.vucem.volume=sonarqube-conf"
  sonardb_data:
    driver: local
    labels:
      - "mx.gob.vucem.volume=sonardb-data"

networks:
  vucem-network:
    driver: bridge
    name: vucem-network
    labels:
      - "mx.gob.vucem.network=main"